name: acu-chatbot-backend
services:
- name: backend
  github:
    repo: egemenulkerr/acu-chatbot
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8080
  
  envs:
  - key: GOOGLE_API_KEY
    scope: RUN_TIME
  # Frontend: egemenulker.com (+ www, http yönlendirmeleri için)
  - key: ALLOWED_ORIGINS
    value: "https://egemenulker.com,https://www.egemenulker.com,http://egemenulker.com,http://www.egemenulker.com,https://king-prawn-app-t5y4u.ondigitalocean.app"
    scope: RUN_TIME
  - key: ENVIRONMENT
    value: production
    scope: RUN_TIME
  - key: LOG_LEVEL
    value: INFO
    scope: RUN_TIME
  - key: USE_EMBEDDINGS
    value: "true"
    scope: RUN_TIME
  
  health_check:
    http_path: /health
    
databases: []
