name: chatbot-uni-backend
services:
- name: backend
  github:
    repo: egemenulkerr/chatbot-uni
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt
  run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
  source_dir: backend
  http_port: 8080
  envs:
  - key: PORT
    value: "8080"
  health_check:
    http_path: /health
  dockerfile_path: Dockerfile
  log_destination_ref: chatbot-logs
static_sites: []
databases: []
