name: chatbot-uni-backend
services:
- name: backend
  github:
    repo: egemenulkerr/chatbot-uni
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8080
  envs:
  - key: GOOGLE_API_KEY
    scope: RUN_TIME
  health_check:
    http_path: /health
static_sites: []
databases: []
