name: chatbot-uni-backend
services:
- name: backend
  github:
    repo: egemenulkerr/chatbot-uni
    branch: main
    deploy_on_push: true
  source_dir: backend
  dockerfile_path: Dockerfile
  http_port: 8080
  envs:
  - key: PORT
    value: "8080"
  health_check:
    http_path: /health
static_sites: []
databases: []
