name: chatbot-uni-backend
services:
- name: chatbot-uni-backend
  github:
    repo: egemenulkerr/chatbot-uni
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  source_dir: backend
  envs:
  - key: GOOGLE_API_KEY
    scope: RUN_TIME
  http_port: 8080
